### ISSUE TITLE
Fix date time styles to match custom label

### ISSUE THREAD

**Issue by juaning** [juaning/emu#21]
Date field style do not match custom label styles

**Comment by radhakri555** [comment]
I tried to give a fix, but I could not see where the date time is been used on the dashboard. PLease let me know the details to help me giving fix.

**Comment by juaning** [comment]
> I tried to give a fix, but I could not see where the date time is been used on the dashboard. PLease let me know the details to help me giving fix.

Hey, thanks for asking and taking the time to check this. The url to get the date field is: /empleados/editar

**Comment by juaning** [comment]
There another one here:

![image](https://user-images.githubusercontent.com/1272442/47238992-5946f380-d3ba-11e8-83cb-596cd3a968cd.png)
