### ISSUE TITLE
Dropdown Styles

### ISSUE THREAD

**Issue by juaning** [juaning/emu#22]
Fix drop down styles to match other fields style

**Comment by marehbergo** [comment]
Are you having problems with conflicting classes? Could you explain better your question?

**Comment by kamaldlk** [comment]
ill take it

**Comment by kamaldlk** [comment]
![screenshot 2018-10-21 at 11 47 22 am](https://user-images.githubusercontent.com/9652523/47263841-3f76ef00-d527-11e8-80ec-a110ed9f5949.png)
