### ISSUE TITLE
Update Health Form form and Model fields

### ISSUE THREAD

**Issue by juaning** [juaning/emu#29]
Update fields to reflect camel case style for fields. Files involved:
webapp/src/views/Employees/healthForm.jsx
api/src/models/HealthModel.ts

**Comment by juaning** [comment]
there's no need for it, at least for the scope of the project at the moment. I might add it later on tho

**Comment by darellkoh** [comment]
@juaning I'd love to take this issue if it's still up for grabs!

**Comment by juaning** [comment]
hey, @darellkoh, it's still available, go for it. thanks

**Comment by darellkoh** [comment]
@juaning Thanks, I'll work on having a PR ready and reach out if any questions arise!

**Comment by juaning** [comment]
let me know if you have any issue, I'll be leaving for an Oktoberfest soon, so I'll probably get back to you tomorrow, or some random gibberish earlier, depending on the beer flow ;)
